Repository linewalks/lwds, pull requests merged in 2021-12, with the labels that each got.

#79 [BUG] style export 설정 오류 해결 및 rollup 셋팅 수정 bug
  dist/index.d.ts
  dist/index.d.ts.map
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  rollup.config.js
  src/index.ts
Labels: bug

#95 빌드 시 typescript 관련 플러그인 경고 해결
  tsconfig.json
Labels: bug

#97 alias path로 type을 import 하지 못하는 버그
  src/components/Icon/IconSet/Action.tsx
  src/components/Icon/IconSet/Navigation.tsx
  src/components/Icon/IconSet/Specific.tsx
  src/components/Icon/IconSet/Toggle.tsx
  styleguide.config.js
Labels: bug

#99 tsconfig.json 을 활용한 styleguide 빌드 시 모듈 접근 불가
  package.json
  styleguide.config.js
  yarn.lock
Labels: bug

#100 LWDS 릴리즈 프로세스 변경
  .versionrc
  package.json
  yarn.lock
Labels: enhancement

#103 LWDS Color palette styleguide 문서 구성
  src/components/Color/Colors.md
  src/components/Color/Colors.tsx
  styleguide.config.js
Labels: documentation

#105 font size styleguide 문서 추가
  src/components/Font/Font.md
  styleguide.config.js
Labels: documentation
